


_select_data:
  aspect-ratios:
    - square
    - portrait
    - portrait-tall
    - landscape
    - landscape-wide

  coloumn-sizes:
    col-6: Half width
    col-12: Full width
    col-4: One Third
    col-3: One Quarter
    col-6_sm-12: Half width Desktop / Stacked on Mobile
    col-4_sm-12: One Third Desktop / Stacked on Mobile
    col-3_sm-12: One Quarter Desktop / Stacked on Mobile